# your proxy setting for libgit2
# proxy: http://localhost:8118
# your github mirror setting, if your network not so good
# mirror: https://hub.yzuu.cf/
# target user directory
user_dir: ~/usr_dir
# cache directory
cache_dir: ~/.rppi_cache/
